### ISSUE TITLE
Theme toggling issue

### ISSUE THREAD

**Issue by rickifox** [WildCodeSchool/tours-php-2009-project2-weshare#22]
Beau boulot sur les transitions de charte graphique, changement rapide, global, uniforme ... Seul soucis mineur on ne peux pas passer directement du rose au turquoise par exemple. Il faut bien se remettre en gris d'abord, ou du moins cliquer deux fois sur le le deuxième bouton, pour voir les changement s'appliquer et la couleur du bouton qui me semble être du noir pourrait laisser penser à un thème sombre classique noir, anthracite, gris et pas nécessairement les nuances de bleu/vert du rendu.

**Comment by KevinRoig** [comment]
Eh oui, pas si simple de passer d'un thème à un autre sans repasser par le thème "classique"... et le bouton gris/noir est effectivement pour dire le thème "sombre" mais les couleurs n'ont pas été validées par le client, c'est plutôt pour le fun pour l'instant ( et le bouton gris/noir n'est pas "relié" aux couleurs du site, c'est un bouton préparé à l'avance.
