### ISSUE TITLE
Links color

### ISSUE THREAD

**Issue by rickifox** [WildCodeSchool/tours-php-2009-project2-weshare#23]
La couleur des liens clicables est parfois trop proche de l'arrière plan et peux les rendre difficilement lisible.

![image](https://user-images.githubusercontent.com/65194501/100237331-19568100-2f2f-11eb-867f-cc8459fc697a.png)

**Comment by KevinRoig** [comment]
Merci pour le retour, c'est déjà en cours de changement par notre équipe de développement.
