### ISSUE TITLE
Footer 

### ISSUE THREAD

**Issue by rickifox** [WildCodeSchool/tours-php-2009-project2-weshare#25]
Vous pourriez peut être mettre vos noms eventuellement lien-clicables vers vos githubs ou linkedIn dans le footer sous "l'equipe" puisque la presence des coordonnées fait quil reste de la place et mette les deux autres section l'un en dessous de l'autre pour équilibrer 

![image](https://user-images.githubusercontent.com/65194501/100237540-5b7fc280-2f2f-11eb-9021-36264a79bcf6.png)

**Comment by KevinRoig** [comment]
Ok, nous faisons part de cette évolution à notre équipe de développement.
