### ISSUE TITLE
Premier titre

### ISSUE THREAD

**Issue by rickifox** [WildCodeSchool/tours-php-2009-project2-weshare#27]
Je ne sais pas si c'est un choix esthétique de l'équipe ou du client mais le premier titre n'a ici pas été séparer comme sur les deux pages suivantes 

![image](https://user-images.githubusercontent.com/65194501/100238044-08f2d600-2f30-11eb-8195-d8197ba4db51.png)

**Comment by rickifox** [comment]
![image](https://user-images.githubusercontent.com/65194501/100238283-4ce5db00-2f30-11eb-83e8-c677dcc608d0.png)

**Comment by rickifox** [comment]
![image](https://user-images.githubusercontent.com/65194501/100238346-66872280-2f30-11eb-9747-20d9b62f2afe.png)

**Comment by KevinRoig** [comment]
La 1ère page n'a pas été encore mise en forme complètement, c'est en cours de modification.
