### ISSUE TITLE
bouton top en mobile 

### ISSUE THREAD

**Issue by rickifox** [WildCodeSchool/tours-php-2009-project2-weshare#29]
emoji top aux  angles relativement droits dans un carré aux angles arrondis sur l'ordi certains utilisateurs

**Comment by AurelieFqt** [comment]
![Capture d’écran du 2020-11-25 15-31-54](https://user-images.githubusercontent.com/70887548/100240959-79e7bd00-2f33-11eb-8328-8e245f361b07.png)

**Comment by KevinRoig** [comment]
Pouvez-vous nous confirmer le navigateur utilisé svp?

**Comment by AurelieFqt** [comment]
Google chrome Mr Roig.
