### ISSUE TITLE
Differentiation des bouton 

### ISSUE THREAD

**Issue by rickifox** [WildCodeSchool/tours-php-2009-project2-weshare#32]
Differentiation des boutons "nouvelle demande" et "je m'enregistre" de la liste des demandes 

![image](https://user-images.githubusercontent.com/65194501/100242005-99cbb080-2f34-11eb-936d-9a4269ea167b.png)

**Comment by KevinRoig** [comment]
Comme vu ensemble, modification effectuée.
![image](https://user-images.githubusercontent.com/70197762/100262364-51b88800-2f4c-11eb-8fb0-817e47296e44.png)
