### ISSUE TITLE
Demandes sur la page d'accueil

### ISSUE THREAD

**Issue by rickifox** [WildCodeSchool/tours-php-2009-project2-weshare#35]
actuellement lorsque je clique sur une demandes j'ai beaucoup de vide mais je dois quand même scroller en desktop pour prendre en charge une demande 

![image](https://user-images.githubusercontent.com/65194501/100245685-9f2afa00-2f38-11eb-87f9-a0a10c99f9ee.png)

**Comment by CeliaBoiss** [comment]
Corrected
