### ISSUE TITLE
Liste express UX issue

### ISSUE THREAD

**Issue by rickifox** [WildCodeSchool/tours-php-2009-project2-weshare#36]
En tant qu'utilisateur, j'ai du mal à comprendre l'objectif et le fonctionnement de cet page de prim abord Je souhaiteraisn plus d'informations quand à son utilité et je voudrais pouvoir valider après avoir cocher eventuellement 

![image](https://user-images.githubusercontent.com/65194501/100246453-70f9ea00-2f39-11eb-80f7-8fc33040b5bd.png)

**Comment by KevinRoig** [comment]
Ok, je rajoute une phrase d'explication : 
je suis "untel" et je prends en charge la demande suivante.
Ca te parait plus explicite?
Par contre, il ne sera pas possible de sélectionner plusieurs demandes et de les valider d'un seul coup.
![image](https://user-images.githubusercontent.com/70197762/100255219-8aa02f00-2f43-11eb-9237-b70e1055fc9e.png)
