### ISSUE TITLE
exception when trying to put "azertyuiop" as phone number

### ISSUE THREAD

**Issue by LucyMerlier** [WildCodeSchool/tours-php-2009-project2-weshare#37]
![Capture d’écran de 2020-11-25 16-21-01](https://user-images.githubusercontent.com/66435395/100247178-570cd700-2f3a-11eb-91a1-5b357668f6b0.png)

I get this when i put "azertyuiop" in the phone number field when trying to create a new user

**Comment by CeliaBoiss** [comment]
The correction is done
