### ISSUE TITLE
Phone number "00"

### ISSUE THREAD

**Issue by FLorianBlm** [WildCodeSchool/tours-php-2009-project2-weshare#39]
When I put my phone number: "00 00 00 00 00" during creating a demand, but display "tel: 00".

**Comment by KevinRoig** [comment]
Yes, the format has to be 0000000000, we will note it after "telephone".

**Comment by CeliaBoiss** [comment]
This issue won't be fix but we gonna display a message for explanation that you have to write a number like this : 0600000000
