### ISSUE TITLE
(Suggestion) Prise en charge pas clair

### ISSUE THREAD

**Issue by FLorianBlm** [WildCodeSchool/tours-php-2009-project2-weshare#40]
![](https://cdn.discordapp.com/attachments/770664029034250250/781180310712221716/Capture_decran_de_2020-11-25_16-30-50.png)

Manque de clarté sur la prise des demandes, notamment dans les rôles des protagonistes

**Comment by KevinRoig** [comment]
J'ai rajouté ceci, est-ce plus explicite?
![image](https://user-images.githubusercontent.com/70197762/100256998-b7554600-2f45-11eb-8d03-1548dc754e8b.png)
