### ISSUE TITLE
Je ne veux pas que les autres fassent des demandes à ma place

### ISSUE THREAD

**Issue by LucyMerlier** [WildCodeSchool/tours-php-2009-project2-weshare#41]
j'ai un problème avec le fait que tout le monde puisse avoir accès aux profils de tout le monde:
je ne veux pas que d'autres personnes puissent faire des demandes ou en accepter en mon nom, mais cela semble tout à fait possible dans l'état actuel du site?

**Comment by CeliaBoiss** [comment]
Alors, en future évolution possible on aurait un système de connection avec identifiant et mdp, mais en l'état non, c'est n'est pas possible
